name: Deploy Azure Web App

on:
  push:
    branches:
      - main

jobs:

  build-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish CalculatorTest.csproj -c Release -o ./publish

    - name: Deploy to Azure App Service (Staging)
      uses: azure/webapps-deploy@v2
      with:
        app-name: CalculatorProgram
        slot-name: staging
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish


  swap-to-production:
    needs: build-deploy
    runs-on: windows-latest
    environment: production   # THIS CREATES APPROVAL STEP

    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Swap Staging to Production
      run: |
        az webapp deployment slot swap \
        --name CalculatorProgram \
        --resource-group Calculator-rg \
        --slot staging \
        --target-slot production
